---
all:
  hosts:
    devops_stage4_server:
      ansible_host: 3.89.62.174
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/todo-key.pem
      ansible_python_interpreter: /usr/bin/python3