- name: Install dependencies
  apt:
    name: ['docker.io', 'docker-compose']
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
